let carrinhoList = [
  {
    id: 1,
    name: "Caderno Universitário",
    img: "images/Caderno.png",
    prices: [37.50, 38.00, 38.00, 37.00 ],
    sizes: ["", "", "", ""],
    description:"Caderno Universitário Capa Dura 100 Folhas, Ideal para o dia a dia na Universidade.",
  },
  {
    id: 2,
    name: "Caderno Brochura",
    img: "images/CadernoBrochuraa.png",
    prices: [7.50, 8.00, 8.00, 8.00],
    sizes: ["", "", "", ""],
    description: "Caderno Brochura Capa Dura Universitário 48 Folhas, Ideal para o dia a dia na escola.",
  },
  {
    id: 3,
    name: "Caderno 10 Matérias",
    img: "images/Caderno10Materiass.png",
    prices: [35.50, 36.00, 36.00, 36,00],
    sizes: ["", "", "", ""],
    description:"Caderno Universitário Capa Dura 10 Matérias 200 Folhas,     Ideal para o dia a dia no Ensino Médio ou na faculdade.",
  },
  {
    id: 4,
    name: "Caneta Esferográfica",
    img: "images/Caneta.png",
    prices: [0.95, 0.97, 0.97, 0.97],
    sizes: ["", "", "", ""],
    description:"Caneta esferográfica clássica e favorita em milhares de lares, Escritórios e escolas no mundo.",
  },
  {
    id: 5,
    name: "Caneta Hidrográfica Colorida",
    img: "images/Canetinha.png",
    prices: [18.00, 18.00, 18.00, 18,00],
    sizes: ["", "", "", ""],
    description:"Caneta Hidrográfica Colorida 12 Cores, Tinta de alta qualidade, Não tóxica.",
  },
  {
    id: 6,
    name: "Pincel Marca Texto",
    img: "images/Stabilo.png",
    prices: [8.50, 8.50, 8.50, 8.50],
    sizes: ["", "", "", ""],
    description:"Pincel Marca Texto, Tinta super fluorescente, Um acessório que se encaixa perfeitamente em qualquer estojo.",
  },
  {
    id: 7,
    name: "EcoLápis Preto Redondo",
    img: "images/Lapis.png",
    prices: [1.20, 1.20, 1.20, 1.20],
    sizes: ["", "", "", ""],
    description:"EcoLápis Preto.",
  },
  {
    id: 8,
    name: "Apontador com Depósito Retangular",
    img: "images/Apontador.png",
    prices: [2.50, 2.55, 2.55, 2.55],
    sizes: ["", "", "", ""],
    description:"Apontador Retangular, Composição de plástico.",
  },
  {
    id: 9,
    name: "Borracha Branca Radex",
    img: "images/borracha.png",
    prices: [2.10, 2.15, 2.15, 2.15],
    sizes: ["", "", "", ""],
    description:"Borracha de formulação especial, que facilita o apagar com maior precisão qualquer tipo de grafite, lapis e lapiseira, sem danificar o papel.",
  },
  {
    id: 10,
    name: "Mochila Cypress Security ",
    img: "images/Mochila.png",
    prices: [399.00, 402.00, 402.00, 402.00],
    sizes: ["", "", "", ""],
    description:"Limpa, contemporânea e protetora, protegem seus itens essenciais do dia a dia, para o que quer que seu dia tenha reservado.",
  },
  {
    id: 11,
    name: "Estojo Liso ",
    img: "images/penal.png",
    prices: [11.00, 13.00, 13.00, 13.00],
    sizes: ["", "", "", ""],
    description:"Possui um formato interno amplo, abrangendo as necessidades, ideal para acompanhar nos estudos, mesas de escritórios.",
  },
  {
    id: 12,
    name: "Kit Mochila com Estojo",
    img: "images/mochila2.png",
    prices: [280.00, 285.00, 285.00, 285.00],
    sizes: ["", "", "", ""],
    description:"É ideal para o seu dia a dia ou para usar como mochila escolar, Capaz de armazenar os itens do dia-a-dia organizadamente.",
  },
];
